import "dotenv/config";

const { PORT, DB_URL, SMTP_ADDRESS, SMTP_PASSWORD, OAUTH_CID, OAUTH_SECRET, OAUTH_REFRESH } = process.env;

export { PORT, DB_URL, SMTP_ADDRESS, SMTP_PASSWORD, OAUTH_CID, OAUTH_SECRET, OAUTH_REFRESH };
